// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// prior
double prior(Rcpp::NumericVector parameter_values, Rcpp::LogicalVector fitted_yn, Rcpp::String likelihood_choice);
RcppExport SEXP _IndianVectorModelling_prior(SEXP parameter_valuesSEXP, SEXP fitted_ynSEXP, SEXP likelihood_choiceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameter_values(parameter_valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type fitted_yn(fitted_ynSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type likelihood_choice(likelihood_choiceSEXP);
    rcpp_result_gen = Rcpp::wrap(prior(parameter_values, fitted_yn, likelihood_choice));
    return rcpp_result_gen;
END_RCPP
}
// likelihood
double likelihood(int N, std::vector <int> obsData, Rcpp::NumericVector fitted_parameters, Rcpp::NumericVector static_parameters, std::vector <double> rainfall, Rcpp::String mortality_density_function, Rcpp::String rainfall_relationship, Rcpp::String rainfall_effect, Rcpp::String decline_type, double sampling_point, Rcpp::StringVector offset_month_vector, Rcpp::StringVector sampling_month_vector, Rcpp::String likelihood_choice, Rcpp::String calc_inside_mosquito_model);
RcppExport SEXP _IndianVectorModelling_likelihood(SEXP NSEXP, SEXP obsDataSEXP, SEXP fitted_parametersSEXP, SEXP static_parametersSEXP, SEXP rainfallSEXP, SEXP mortality_density_functionSEXP, SEXP rainfall_relationshipSEXP, SEXP rainfall_effectSEXP, SEXP decline_typeSEXP, SEXP sampling_pointSEXP, SEXP offset_month_vectorSEXP, SEXP sampling_month_vectorSEXP, SEXP likelihood_choiceSEXP, SEXP calc_inside_mosquito_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::vector <int> >::type obsData(obsDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fitted_parameters(fitted_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type static_parameters(static_parametersSEXP);
    Rcpp::traits::input_parameter< std::vector <double> >::type rainfall(rainfallSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type mortality_density_function(mortality_density_functionSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_relationship(rainfall_relationshipSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_effect(rainfall_effectSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type decline_type(decline_typeSEXP);
    Rcpp::traits::input_parameter< double >::type sampling_point(sampling_pointSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type offset_month_vector(offset_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sampling_month_vector(sampling_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type likelihood_choice(likelihood_choiceSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type calc_inside_mosquito_model(calc_inside_mosquito_modelSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihood(N, obsData, fitted_parameters, static_parameters, rainfall, mortality_density_function, rainfall_relationship, rainfall_effect, decline_type, sampling_point, offset_month_vector, sampling_month_vector, likelihood_choice, calc_inside_mosquito_model));
    return rcpp_result_gen;
END_RCPP
}
// posterior
double posterior(int N, std::vector <int> obsData, Rcpp::NumericVector fitted_parameters, Rcpp::NumericVector static_parameters, std::vector <double> rainfall, Rcpp::LogicalVector fitted_yn, Rcpp::String mortality_density_function, Rcpp::String rainfall_relationship, Rcpp::String rainfall_effect, Rcpp::String decline_type, double sampling_point, Rcpp::StringVector offset_month_vector, Rcpp::StringVector sampling_month_vector, Rcpp::String likelihood_choice, Rcpp::String calc_inside_mosquito_model);
RcppExport SEXP _IndianVectorModelling_posterior(SEXP NSEXP, SEXP obsDataSEXP, SEXP fitted_parametersSEXP, SEXP static_parametersSEXP, SEXP rainfallSEXP, SEXP fitted_ynSEXP, SEXP mortality_density_functionSEXP, SEXP rainfall_relationshipSEXP, SEXP rainfall_effectSEXP, SEXP decline_typeSEXP, SEXP sampling_pointSEXP, SEXP offset_month_vectorSEXP, SEXP sampling_month_vectorSEXP, SEXP likelihood_choiceSEXP, SEXP calc_inside_mosquito_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::vector <int> >::type obsData(obsDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fitted_parameters(fitted_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type static_parameters(static_parametersSEXP);
    Rcpp::traits::input_parameter< std::vector <double> >::type rainfall(rainfallSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type fitted_yn(fitted_ynSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type mortality_density_function(mortality_density_functionSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_relationship(rainfall_relationshipSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_effect(rainfall_effectSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type decline_type(decline_typeSEXP);
    Rcpp::traits::input_parameter< double >::type sampling_point(sampling_pointSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type offset_month_vector(offset_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sampling_month_vector(sampling_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type likelihood_choice(likelihood_choiceSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type calc_inside_mosquito_model(calc_inside_mosquito_modelSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior(N, obsData, fitted_parameters, static_parameters, rainfall, fitted_yn, mortality_density_function, rainfall_relationship, rainfall_effect, decline_type, sampling_point, offset_month_vector, sampling_month_vector, likelihood_choice, calc_inside_mosquito_model));
    return rcpp_result_gen;
END_RCPP
}
// proposal_SD_adapter
Rcpp::List proposal_SD_adapter(double accepted_variable, double current_iteration, double iteration_cooling_began, double current_scaling_factor, arma::mat mu_previous, arma::mat current_parameter_values, arma::mat current_covariance_matrix);
RcppExport SEXP _IndianVectorModelling_proposal_SD_adapter(SEXP accepted_variableSEXP, SEXP current_iterationSEXP, SEXP iteration_cooling_beganSEXP, SEXP current_scaling_factorSEXP, SEXP mu_previousSEXP, SEXP current_parameter_valuesSEXP, SEXP current_covariance_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type accepted_variable(accepted_variableSEXP);
    Rcpp::traits::input_parameter< double >::type current_iteration(current_iterationSEXP);
    Rcpp::traits::input_parameter< double >::type iteration_cooling_began(iteration_cooling_beganSEXP);
    Rcpp::traits::input_parameter< double >::type current_scaling_factor(current_scaling_factorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu_previous(mu_previousSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type current_parameter_values(current_parameter_valuesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type current_covariance_matrix(current_covariance_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(proposal_SD_adapter(accepted_variable, current_iteration, iteration_cooling_began, current_scaling_factor, mu_previous, current_parameter_values, current_covariance_matrix));
    return rcpp_result_gen;
END_RCPP
}
// mvrnormArma
Rcpp::List mvrnormArma(arma::mat mu, arma::mat sigma);
RcppExport SEXP _IndianVectorModelling_mvrnormArma(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// general_mosquito_population_model
Rcpp::List general_mosquito_population_model(int start_time, int end, Rcpp::NumericVector fitted_parameters, Rcpp::NumericVector static_parameters, std::vector<double> rainfall, Rcpp::String mortality_density_function, Rcpp::String rainfall_relationship, Rcpp::String rainfall_effect, Rcpp::String decline_type, Rcpp::String calc_inside_mosquito_model, std::vector<double> input_Exponential_Weighting_Factors_Static, std::vector<double> input_Exponential_Weighting_Factors_Rainfall, std::vector<double> input_Exponential_Normalisation_Factors_Static, std::vector<double> input_Exponential_Normalisation_Factors_Rainfall, int full_output);
RcppExport SEXP _IndianVectorModelling_general_mosquito_population_model(SEXP start_timeSEXP, SEXP endSEXP, SEXP fitted_parametersSEXP, SEXP static_parametersSEXP, SEXP rainfallSEXP, SEXP mortality_density_functionSEXP, SEXP rainfall_relationshipSEXP, SEXP rainfall_effectSEXP, SEXP decline_typeSEXP, SEXP calc_inside_mosquito_modelSEXP, SEXP input_Exponential_Weighting_Factors_StaticSEXP, SEXP input_Exponential_Weighting_Factors_RainfallSEXP, SEXP input_Exponential_Normalisation_Factors_StaticSEXP, SEXP input_Exponential_Normalisation_Factors_RainfallSEXP, SEXP full_outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type start_time(start_timeSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fitted_parameters(fitted_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type static_parameters(static_parametersSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type rainfall(rainfallSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type mortality_density_function(mortality_density_functionSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_relationship(rainfall_relationshipSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_effect(rainfall_effectSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type decline_type(decline_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type calc_inside_mosquito_model(calc_inside_mosquito_modelSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type input_Exponential_Weighting_Factors_Static(input_Exponential_Weighting_Factors_StaticSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type input_Exponential_Weighting_Factors_Rainfall(input_Exponential_Weighting_Factors_RainfallSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type input_Exponential_Normalisation_Factors_Static(input_Exponential_Normalisation_Factors_StaticSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type input_Exponential_Normalisation_Factors_Rainfall(input_Exponential_Normalisation_Factors_RainfallSEXP);
    Rcpp::traits::input_parameter< int >::type full_output(full_outputSEXP);
    rcpp_result_gen = Rcpp::wrap(general_mosquito_population_model(start_time, end, fitted_parameters, static_parameters, rainfall, mortality_density_function, rainfall_relationship, rainfall_effect, decline_type, calc_inside_mosquito_model, input_Exponential_Weighting_Factors_Static, input_Exponential_Weighting_Factors_Rainfall, input_Exponential_Normalisation_Factors_Static, input_Exponential_Normalisation_Factors_Rainfall, full_output));
    return rcpp_result_gen;
END_RCPP
}
// Hill_Function
double Hill_Function(double rainfall, double K_max, double a, double b);
RcppExport SEXP _IndianVectorModelling_Hill_Function(SEXP rainfallSEXP, SEXP K_maxSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rainfall(rainfallSEXP);
    Rcpp::traits::input_parameter< double >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(Hill_Function(rainfall, K_max, a, b));
    return rcpp_result_gen;
END_RCPP
}
// initial_state_sample
std::vector <int> initial_state_sample(Rcpp::NumericVector fitted_parameters, Rcpp::NumericVector static_parameters, Rcpp::String mortality_density_function);
RcppExport SEXP _IndianVectorModelling_initial_state_sample(SEXP fitted_parametersSEXP, SEXP static_parametersSEXP, SEXP mortality_density_functionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fitted_parameters(fitted_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type static_parameters(static_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type mortality_density_function(mortality_density_functionSEXP);
    rcpp_result_gen = Rcpp::wrap(initial_state_sample(fitted_parameters, static_parameters, mortality_density_function));
    return rcpp_result_gen;
END_RCPP
}
// min_output_particle_filter
double min_output_particle_filter(int N, std::vector <int> obsData, Rcpp::NumericVector fitted_parameters, Rcpp::NumericVector static_parameters, std::vector <double> rainfall, Rcpp::String mortality_density_function, Rcpp::String rainfall_relationship, Rcpp::String rainfall_effect, Rcpp::String decline_type, double sampling_point, Rcpp::StringVector offset_month_vector, Rcpp::StringVector sampling_month_vector, Rcpp::String likelihood_choice, Rcpp::String calc_inside_mosquito_model);
RcppExport SEXP _IndianVectorModelling_min_output_particle_filter(SEXP NSEXP, SEXP obsDataSEXP, SEXP fitted_parametersSEXP, SEXP static_parametersSEXP, SEXP rainfallSEXP, SEXP mortality_density_functionSEXP, SEXP rainfall_relationshipSEXP, SEXP rainfall_effectSEXP, SEXP decline_typeSEXP, SEXP sampling_pointSEXP, SEXP offset_month_vectorSEXP, SEXP sampling_month_vectorSEXP, SEXP likelihood_choiceSEXP, SEXP calc_inside_mosquito_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::vector <int> >::type obsData(obsDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fitted_parameters(fitted_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type static_parameters(static_parametersSEXP);
    Rcpp::traits::input_parameter< std::vector <double> >::type rainfall(rainfallSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type mortality_density_function(mortality_density_functionSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_relationship(rainfall_relationshipSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_effect(rainfall_effectSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type decline_type(decline_typeSEXP);
    Rcpp::traits::input_parameter< double >::type sampling_point(sampling_pointSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type offset_month_vector(offset_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sampling_month_vector(sampling_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type likelihood_choice(likelihood_choiceSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type calc_inside_mosquito_model(calc_inside_mosquito_modelSEXP);
    rcpp_result_gen = Rcpp::wrap(min_output_particle_filter(N, obsData, fitted_parameters, static_parameters, rainfall, mortality_density_function, rainfall_relationship, rainfall_effect, decline_type, sampling_point, offset_month_vector, sampling_month_vector, likelihood_choice, calc_inside_mosquito_model));
    return rcpp_result_gen;
END_RCPP
}
// full_output_particle_filter
Rcpp::List full_output_particle_filter(int N, std::vector <int> obsData, Rcpp::NumericVector fitted_parameters, Rcpp::NumericVector static_parameters, std::vector <double> rainfall, Rcpp::String mortality_density_function, Rcpp::String rainfall_relationship, Rcpp::String rainfall_effect, Rcpp::String decline_type, double sampling_point, Rcpp::StringVector offset_month_vector, Rcpp::StringVector sampling_month_vector, Rcpp::String likelihood_choice, Rcpp::String calc_inside_mosquito_model);
RcppExport SEXP _IndianVectorModelling_full_output_particle_filter(SEXP NSEXP, SEXP obsDataSEXP, SEXP fitted_parametersSEXP, SEXP static_parametersSEXP, SEXP rainfallSEXP, SEXP mortality_density_functionSEXP, SEXP rainfall_relationshipSEXP, SEXP rainfall_effectSEXP, SEXP decline_typeSEXP, SEXP sampling_pointSEXP, SEXP offset_month_vectorSEXP, SEXP sampling_month_vectorSEXP, SEXP likelihood_choiceSEXP, SEXP calc_inside_mosquito_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::vector <int> >::type obsData(obsDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fitted_parameters(fitted_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type static_parameters(static_parametersSEXP);
    Rcpp::traits::input_parameter< std::vector <double> >::type rainfall(rainfallSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type mortality_density_function(mortality_density_functionSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_relationship(rainfall_relationshipSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_effect(rainfall_effectSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type decline_type(decline_typeSEXP);
    Rcpp::traits::input_parameter< double >::type sampling_point(sampling_pointSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type offset_month_vector(offset_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sampling_month_vector(sampling_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type likelihood_choice(likelihood_choiceSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type calc_inside_mosquito_model(calc_inside_mosquito_modelSEXP);
    rcpp_result_gen = Rcpp::wrap(full_output_particle_filter(N, obsData, fitted_parameters, static_parameters, rainfall, mortality_density_function, rainfall_relationship, rainfall_effect, decline_type, sampling_point, offset_month_vector, sampling_month_vector, likelihood_choice, calc_inside_mosquito_model));
    return rcpp_result_gen;
END_RCPP
}
// Negative_Binomial
double Negative_Binomial(double k, double n, double r, double p);
RcppExport SEXP _IndianVectorModelling_Negative_Binomial(SEXP kSEXP, SEXP nSEXP, SEXP rSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Negative_Binomial(k, n, r, p));
    return rcpp_result_gen;
END_RCPP
}
// Poisson
double Poisson(double observed_data, double model_output, double population_fraction);
RcppExport SEXP _IndianVectorModelling_Poisson(SEXP observed_dataSEXP, SEXP model_outputSEXP, SEXP population_fractionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type observed_data(observed_dataSEXP);
    Rcpp::traits::input_parameter< double >::type model_output(model_outputSEXP);
    Rcpp::traits::input_parameter< double >::type population_fraction(population_fractionSEXP);
    rcpp_result_gen = Rcpp::wrap(Poisson(observed_data, model_output, population_fraction));
    return rcpp_result_gen;
END_RCPP
}
// Particle_Weight_Normalisation
std::vector <double> Particle_Weight_Normalisation(std::vector <double> particle_weights);
RcppExport SEXP _IndianVectorModelling_Particle_Weight_Normalisation(SEXP particle_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector <double> >::type particle_weights(particle_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(Particle_Weight_Normalisation(particle_weights));
    return rcpp_result_gen;
END_RCPP
}
// weighted_sampling_with_replacement
std::vector<int> weighted_sampling_with_replacement(int n, std::vector<double> prob, double p_tot, int K);
RcppExport SEXP _IndianVectorModelling_weighted_sampling_with_replacement(SEXP nSEXP, SEXP probSEXP, SEXP p_totSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type prob(probSEXP);
    Rcpp::traits::input_parameter< double >::type p_tot(p_totSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_sampling_with_replacement(n, prob, p_tot, K));
    return rcpp_result_gen;
END_RCPP
}
// run_particle_MCMC
Rcpp::List run_particle_MCMC(int N, int start_sd_adaptation, int end_sd_adaptation, int number_of_iterations, std::vector <double> initial_sds, Rcpp::NumericVector model_parameters, Rcpp::NumericVector static_parameters, Rcpp::LogicalVector fitted_yn, std::vector <double> rainfall, std::vector <int> obsData, Rcpp::String mortality_density_function, Rcpp::String rainfall_relationship, Rcpp::String rainfall_effect, Rcpp::String decline_type, double sampling_point, Rcpp::StringVector offset_month_vector, Rcpp::StringVector sampling_month_vector, Rcpp::String likelihood_choice, int print_output, Rcpp::String calc_inside_mosquito_model, int all_output);
RcppExport SEXP _IndianVectorModelling_run_particle_MCMC(SEXP NSEXP, SEXP start_sd_adaptationSEXP, SEXP end_sd_adaptationSEXP, SEXP number_of_iterationsSEXP, SEXP initial_sdsSEXP, SEXP model_parametersSEXP, SEXP static_parametersSEXP, SEXP fitted_ynSEXP, SEXP rainfallSEXP, SEXP obsDataSEXP, SEXP mortality_density_functionSEXP, SEXP rainfall_relationshipSEXP, SEXP rainfall_effectSEXP, SEXP decline_typeSEXP, SEXP sampling_pointSEXP, SEXP offset_month_vectorSEXP, SEXP sampling_month_vectorSEXP, SEXP likelihood_choiceSEXP, SEXP print_outputSEXP, SEXP calc_inside_mosquito_modelSEXP, SEXP all_outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type start_sd_adaptation(start_sd_adaptationSEXP);
    Rcpp::traits::input_parameter< int >::type end_sd_adaptation(end_sd_adaptationSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_iterations(number_of_iterationsSEXP);
    Rcpp::traits::input_parameter< std::vector <double> >::type initial_sds(initial_sdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type model_parameters(model_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type static_parameters(static_parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type fitted_yn(fitted_ynSEXP);
    Rcpp::traits::input_parameter< std::vector <double> >::type rainfall(rainfallSEXP);
    Rcpp::traits::input_parameter< std::vector <int> >::type obsData(obsDataSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type mortality_density_function(mortality_density_functionSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_relationship(rainfall_relationshipSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type rainfall_effect(rainfall_effectSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type decline_type(decline_typeSEXP);
    Rcpp::traits::input_parameter< double >::type sampling_point(sampling_pointSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type offset_month_vector(offset_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sampling_month_vector(sampling_month_vectorSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type likelihood_choice(likelihood_choiceSEXP);
    Rcpp::traits::input_parameter< int >::type print_output(print_outputSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type calc_inside_mosquito_model(calc_inside_mosquito_modelSEXP);
    Rcpp::traits::input_parameter< int >::type all_output(all_outputSEXP);
    rcpp_result_gen = Rcpp::wrap(run_particle_MCMC(N, start_sd_adaptation, end_sd_adaptation, number_of_iterations, initial_sds, model_parameters, static_parameters, fitted_yn, rainfall, obsData, mortality_density_function, rainfall_relationship, rainfall_effect, decline_type, sampling_point, offset_month_vector, sampling_month_vector, likelihood_choice, print_output, calc_inside_mosquito_model, all_output));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IndianVectorModelling_prior", (DL_FUNC) &_IndianVectorModelling_prior, 3},
    {"_IndianVectorModelling_likelihood", (DL_FUNC) &_IndianVectorModelling_likelihood, 14},
    {"_IndianVectorModelling_posterior", (DL_FUNC) &_IndianVectorModelling_posterior, 15},
    {"_IndianVectorModelling_proposal_SD_adapter", (DL_FUNC) &_IndianVectorModelling_proposal_SD_adapter, 7},
    {"_IndianVectorModelling_mvrnormArma", (DL_FUNC) &_IndianVectorModelling_mvrnormArma, 2},
    {"_IndianVectorModelling_general_mosquito_population_model", (DL_FUNC) &_IndianVectorModelling_general_mosquito_population_model, 15},
    {"_IndianVectorModelling_Hill_Function", (DL_FUNC) &_IndianVectorModelling_Hill_Function, 4},
    {"_IndianVectorModelling_initial_state_sample", (DL_FUNC) &_IndianVectorModelling_initial_state_sample, 3},
    {"_IndianVectorModelling_min_output_particle_filter", (DL_FUNC) &_IndianVectorModelling_min_output_particle_filter, 14},
    {"_IndianVectorModelling_full_output_particle_filter", (DL_FUNC) &_IndianVectorModelling_full_output_particle_filter, 14},
    {"_IndianVectorModelling_Negative_Binomial", (DL_FUNC) &_IndianVectorModelling_Negative_Binomial, 4},
    {"_IndianVectorModelling_Poisson", (DL_FUNC) &_IndianVectorModelling_Poisson, 3},
    {"_IndianVectorModelling_Particle_Weight_Normalisation", (DL_FUNC) &_IndianVectorModelling_Particle_Weight_Normalisation, 1},
    {"_IndianVectorModelling_weighted_sampling_with_replacement", (DL_FUNC) &_IndianVectorModelling_weighted_sampling_with_replacement, 4},
    {"_IndianVectorModelling_run_particle_MCMC", (DL_FUNC) &_IndianVectorModelling_run_particle_MCMC, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_IndianVectorModelling(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
