# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
prior_seq_proposals <- function(parameter_values, prior_choice, fitted_yn) {
    .Call('_IndianVectorModelling_prior_seq_proposals', PACKAGE = 'IndianVectorModelling', parameter_values, prior_choice, fitted_yn)
}

#' @export
likelihood_function <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function) {
    .Call('_IndianVectorModelling_likelihood_function', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function)
}

#' @export
posterior_seq_proposals <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function, parameter_value, parameter_index, prior_choice, fitted_yn) {
    .Call('_IndianVectorModelling_posterior_seq_proposals', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function, parameter_value, parameter_index, prior_choice, fitted_yn)
}

#' @export
seq_proposal_function <- function(sd, current_parameter_value) {
    .Call('_IndianVectorModelling_seq_proposal_function', PACKAGE = 'IndianVectorModelling', sd, current_parameter_value)
}

#' @export
seq_proposal_SD_adapter <- function(accepted_variable, current_iteration, iteration_cooling_began, current_sd) {
    .Call('_IndianVectorModelling_seq_proposal_SD_adapter', PACKAGE = 'IndianVectorModelling', accepted_variable, current_iteration, iteration_cooling_began, current_sd)
}

#' @export
joint_proposal_SD_adapter <- function(accepted_variable, current_iteration, iteration_cooling_began, current_scaling_factor, mu_previous, current_parameter_values, current_covariance_matrix) {
    .Call('_IndianVectorModelling_joint_proposal_SD_adapter', PACKAGE = 'IndianVectorModelling', accepted_variable, current_iteration, iteration_cooling_began, current_scaling_factor, mu_previous, current_parameter_values, current_covariance_matrix)
}

#' @export
posterior_joint_proposals <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function, prior_choice, fitted_yn) {
    .Call('_IndianVectorModelling_posterior_joint_proposals', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function, prior_choice, fitted_yn)
}

#' @export
mosquito_population_model <- function(start_time, end, fitted_parameters, static_parameters, rainfall, mortality_density_function) {
    .Call('_IndianVectorModelling_mosquito_population_model', PACKAGE = 'IndianVectorModelling', start_time, end, fitted_parameters, static_parameters, rainfall, mortality_density_function)
}

#' @export
mvrnormArma <- function(mu, sigma) {
    .Call('_IndianVectorModelling_mvrnormArma', PACKAGE = 'IndianVectorModelling', mu, sigma)
}

#' @export
min_output_particle_filter <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function) {
    .Call('_IndianVectorModelling_min_output_particle_filter', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function)
}

#' @export
full_output_particle_filter <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function) {
    .Call('_IndianVectorModelling_full_output_particle_filter', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function)
}

#' @export
Negative_Binomial <- function(k, n, r, p) {
    .Call('_IndianVectorModelling_Negative_Binomial', PACKAGE = 'IndianVectorModelling', k, n, r, p)
}

#' @export
Particle_Weight_Normalisation <- function(particle_weights) {
    .Call('_IndianVectorModelling_Particle_Weight_Normalisation', PACKAGE = 'IndianVectorModelling', particle_weights)
}

#' @export
initial_state_sample <- function(fitted_parameters, static_parameters, initial_K) {
    .Call('_IndianVectorModelling_initial_state_sample', PACKAGE = 'IndianVectorModelling', fitted_parameters, static_parameters, initial_K)
}

#' @export
weighted_sampling_with_replacement <- function(n, prob, p_tot, K) {
    .Call('_IndianVectorModelling_weighted_sampling_with_replacement', PACKAGE = 'IndianVectorModelling', n, prob, p_tot, K)
}

#' @export
runMCMC_joint_props <- function(start_sd_adaptation, end_sd_adaptation, number_of_iterations, initial_sds, model_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice, fitted_yn) {
    .Call('_IndianVectorModelling_runMCMC_joint_props', PACKAGE = 'IndianVectorModelling', start_sd_adaptation, end_sd_adaptation, number_of_iterations, initial_sds, model_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice, fitted_yn)
}

#' @export
runMCMC_seq_props <- function(start_sd_adaptation, end_sd_adaptation, acceptance_ratio, sd_proposals, number_of_iterations, model_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice, fitted_yn) {
    .Call('_IndianVectorModelling_runMCMC_seq_props', PACKAGE = 'IndianVectorModelling', start_sd_adaptation, end_sd_adaptation, acceptance_ratio, sd_proposals, number_of_iterations, model_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice, fitted_yn)
}

#' @export
testerr <- function(start_sd_adaptation, end_sd_adaptation, number_of_iterations, initial_sds, model_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice, fitted_yn) {
    .Call('_IndianVectorModelling_testerr', PACKAGE = 'IndianVectorModelling', start_sd_adaptation, end_sd_adaptation, number_of_iterations, initial_sds, model_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice, fitted_yn)
}

