# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

full_output_particle_filter <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function) {
    .Call('_IndianVectorModelling_full_output_particle_filter', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function)
}

initial_state_sample <- function(fitted_parameters, static_parameters) {
    .Call('_IndianVectorModelling_initial_state_sample', PACKAGE = 'IndianVectorModelling', fitted_parameters, static_parameters)
}

prior <- function(parameter_values, prior_choice) {
    .Call('_IndianVectorModelling_prior', PACKAGE = 'IndianVectorModelling', parameter_values, prior_choice)
}

likelihood_function <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function) {
    .Call('_IndianVectorModelling_likelihood_function', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function)
}

posterior <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function, parameter_value, parameter_index, prior_choice) {
    .Call('_IndianVectorModelling_posterior', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function, parameter_value, parameter_index, prior_choice)
}

min_output_particle_filter <- function(N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function) {
    .Call('_IndianVectorModelling_min_output_particle_filter', PACKAGE = 'IndianVectorModelling', N, rainfall, obsData, number_of_datapoints, data_timeframe, fitted_parameters, static_parameters, density_function)
}

mosquito_population_model <- function(start_time, end, fitted_parameters, static_parameters, rainfall, density_function) {
    .Call('_IndianVectorModelling_mosquito_population_model', PACKAGE = 'IndianVectorModelling', start_time, end, fitted_parameters, static_parameters, rainfall, density_function)
}

Negative_Binomial <- function(k, n, r, p) {
    .Call('_IndianVectorModelling_Negative_Binomial', PACKAGE = 'IndianVectorModelling', k, n, r, p)
}

Particle_Weight_Normalisation <- function(particle_weights) {
    .Call('_IndianVectorModelling_Particle_Weight_Normalisation', PACKAGE = 'IndianVectorModelling', particle_weights)
}

proposal_function <- function(sd, current_parameter_value) {
    .Call('_IndianVectorModelling_proposal_function', PACKAGE = 'IndianVectorModelling', sd, current_parameter_value)
}

proposal_SD_adapter <- function(current_sd, acceptance_ratio, current_acceptance_ratio, max_sd) {
    .Call('_IndianVectorModelling_proposal_SD_adapter', PACKAGE = 'IndianVectorModelling', current_sd, acceptance_ratio, current_acceptance_ratio, max_sd)
}

proposal_SD_adapter_mark_two <- function(current_sd, current_acceptance_ratio, max_sd, cooling_factor, current_iteration, iteration_cooling_began) {
    .Call('_IndianVectorModelling_proposal_SD_adapter_mark_two', PACKAGE = 'IndianVectorModelling', current_sd, current_acceptance_ratio, max_sd, cooling_factor, current_iteration, iteration_cooling_began)
}

runMCMC <- function(start_sd_adaptation, end_sd_adaptation, max_sd, acceptance_ratio, sd_proposals, number_of_iterations, parameters_to_be_fitted, fitted_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice) {
    .Call('_IndianVectorModelling_runMCMC', PACKAGE = 'IndianVectorModelling', start_sd_adaptation, end_sd_adaptation, max_sd, acceptance_ratio, sd_proposals, number_of_iterations, parameters_to_be_fitted, fitted_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice)
}

runMCMC_alt_tune <- function(start_sd_adaptation, end_sd_adaptation, max_sd, acceptance_ratio, sd_proposals, number_of_iterations, parameters_to_be_fitted, fitted_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice) {
    .Call('_IndianVectorModelling_runMCMC_alt_tune', PACKAGE = 'IndianVectorModelling', start_sd_adaptation, end_sd_adaptation, max_sd, acceptance_ratio, sd_proposals, number_of_iterations, parameters_to_be_fitted, fitted_parameters, static_parameters, N, rainfall, obsData, number_of_datapoints, data_timeframe, density_function, prior_choice)
}

weighted_sampling <- function(n, prob, p_tot, K) {
    .Call('_IndianVectorModelling_weighted_sampling', PACKAGE = 'IndianVectorModelling', n, prob, p_tot, K)
}

